### ISSUE TITLE
ユーザ定義プログラムから入力されたコマンドに必要な brain 以外の brain は取得できないようにする

### ISSUE THREAD

**Issue by nyamadori** [nyamadori/metabot#6]
# 概要

* bot の開発者が作ったプログラム（=ユーザ定義プログラム）から、入力コマンドに必要な brain 以外の brain は取得できないようにする
  - ユーザ定義プログラムが他の bot の brain を書き換えることを防ぐため

# 手段

* Firebase Admin SDK によって、好き勝手データを書き換えられることを防げばいい
  - Firebase プロジェクトを、Slack イベントを受け取り Bot のデータを管理する部分と、ユーザ定義プログラムを実行する部分とに分割
  - 前者のプロジェクト（`metabot` プロジェクト）は、Firebase Admin SDK で自由にデータの読み書きができるが、後者（`metabot-exector` プロジェクト）はそもそもプロジェクトが異なるので、明示的にサービスアカウントを用意しない限り、Bot のデータを自由に読み書きができない
  - Bot データを管理する metabot プロジェクト側は、目的が実現できるよう適切に Firestore セキュリティルールを適用
  - metabot-exector からは Firebase クライアント用ライブラリを使い、metabot プロジェクトの Firestore にアクセス

# Todo

* [x] プロジェクトの分割
* [x] brain のモックデータに適当なトークン（Brain トークン）を追加
* [x] metabot-exector が認証するエンドポイントを metabot 側に 用意
  - https://firebase.google.com/docs/auth/admin/create-custom-tokens?hl=ja
  - 認証は brain トークンで行う
  - レスポンスは Firebase Auth のカスタムトークンと Bot の情報
    - 実際にはユーザ定義プログラムとかを送ったりする
* [x] Brain トークンで認証されていないと brain データが見られないようにセキュリティルールを記述

**Comment by nyamadori** [comment]
firebase-admin 用の Service Account がプロジェクトに存在する限り、firebase-admin を使って自由に 
 Firestore にアクセスできてしまうので、前段と後段で GCP プロジェクトを分離し、後段 CF が前段側の Firestore に自由なアクセスが出来ないようにする。
後段 CF は、クライアントとして 前段側の Firestore にアクセスする。
